"""initial tables

Revision ID: 2deaa18cec26
Revises: 
Create Date: 2026-09-10 10:53:40.015937
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2deaa18cec26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
