"""add orders and inventory tables

Revision ID: e0b1417e1499
Revises: 2deaa18cec26
Create Date: 2026-09-10 11:08:52.331826
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e0b1417e1499'
down_revision: Union[str, None] = '2deaa18cec26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
